/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wflxbcuoqzrwbacsfvvt"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmbHhiY3VvcXpyd2JhY3NmdnZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU0NDQ2MDcsImV4cCI6MjA4MTAyMDYwN30.d-O1zem8avTN-80mJwFDPP50S_Gw5yEdqmpW89LLfJo"